version: '3.1'
services:
  metrics-db:
    image: influxdb
    hostname: metrics-db
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb
    networks:
      - back_tier

  search-db:
    image: postgres:9
    container_name: "ndb_search_db"
    hostname: search-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - search_data:/var/lib/postgresql/data
      - ./datastore/search:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  data:
    image: mouselightdatabrowser/data
    container_name: "ndb_data"
    hostname: ndb-data
    environment:
      NODE_ENV: production
    volumes:
      - /opt/data:/opt/data
    networks:
      - back_tier

  search-api-1:
    image: mouselightdatabrowser/search-api
    container_name: "ndb_search-api-1"
    hostname: search-api-1
    environment:
      NODE_ENV: production
      NEURON_EXPLORER_RELEASE: public
    networks:
      - back_tier
    links:
      - search-db

  search-api-2:
    image: mouselightdatabrowser/search-api
    container_name: "ndb_search-api-2"
    hostname: search-api-2
    environment:
      NODE_ENV: production
      NEURON_EXPLORER_RELEASE: public
    networks:
      - back_tier
    links:
      - search-db

  search-api-3:
    image: mouselightdatabrowser/search-api
    container_name: "ndb_search-api-3"
    hostname: search-api-3
    environment:
      NODE_ENV: production
      NEURON_EXPLORER_RELEASE: public
    networks:
      - back_tier
    links:
      - search-db

  search-client-1:
     image: mouselightdatabrowser/search-client
     hostname: search-client-1
     container_name: "ndb_search-client-1"
     environment:
       NODE_ENV: production
       TRANSFORM_API_HOST: search-api-1
     networks:
       - back_tier
     links:
       - search-api-1

  search-client-2:
     image: mouselightdatabrowser/search-client
     hostname: search-client-2
     container_name: "ndb_search-client-2"
     environment:
       NODE_ENV: production
       TRANSFORM_API_HOST: search-api-3
     networks:
       - back_tier
     links:
       - search-api-3

  export-api-1:
    image: mouselightdatabrowser/export-api
    container_name: "ndb_export-api-1"
    hostname: export-api-1
    environment:
      NODE_ENV: production
    volumes:
       - /data/export:/opt/data/export
    networks:
      - back_tier
    links:
      - metrics-db

  export-api-2:
    image: mouselightdatabrowser/export-api
    container_name: "ndb_export-api-2"
    hostname: export-api-2
    environment:
      NODE_ENV: production
    volumes:
       - /data/export:/opt/data/export
    networks:
      - back_tier
    links:
      - metrics-db

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    volumes:
      - nginx_log:/var/log/nginx
    ports:
      - 80:80
    networks:
      - back_tier
    links:
      - export-api-1
      - export-api-2
      - search-api-1
      - search-api-2
      - search-api-3
      - search-client-1
      - search-client-2

volumes:
  influx_data:
  influx_config:
  search_data:
  nginx_log:

networks:
  back_tier:
