version: '3.1'
services:
  metrics-db:
    image: influxdb:1.5
    hostname: metrics-db
    ports:
      - 8086:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb
    networks:
      - back_tier

  search-db:
    image: postgres:9
    hostname: search-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DATABASE_PW}
    volumes:
      - search_data:/var/lib/postgresql/data
      - ./datastore/search:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  search-api-1:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api-1
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: public
      DATABASE_PW:
    networks:
      - back_tier
    links:
      - search-db
      - metrics-db

  search-api-2:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api-2
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: public
      DATABASE_PW:
    networks:
      - back_tier
    links:
      - search-db
      - metrics-db

  search-api-3:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api-3
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: public
      DATABASE_PW:
    networks:
      - back_tier
    links:
      - search-db
      - metrics-db

  search-api-4:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api-4
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: public
      DATABASE_PW:
    networks:
      - back_tier
    links:
      - search-db
      - metrics-db

  search-api-5:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api-5
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: public
      DATABASE_PW:
    networks:
      - back_tier
    links:
      - search-db
      - metrics-db

  search-api-6:
    image: mouselightdatabrowser/search-api:1.4
    hostname: search-api-6
    environment:
      NODE_ENV: production
      NEURON_BROWSER_RELEASE: public
      DATABASE_PW:
    networks:
      - back_tier
    links:
      - search-db
      - metrics-db

  search-client-1:
     image: mouselightdatabrowser/search-client:1.4
     hostname: search-client-1
     environment:
       NODE_ENV: production
       SEARCH_API_HOST: search-api-1
       NB_OMIT_PASSWORD: "omit"
     networks:
       - back_tier
     links:
       - search-api-1

  search-client-2:
     image: mouselightdatabrowser/search-client:1.4
     hostname: search-client-2
     environment:
       NODE_ENV: production
       SEARCH_API_HOST: search-api-2
       NB_OMIT_PASSWORD: "omit"
     networks:
       - back_tier
     links:
       - search-api-2

  export-api-1:
    image: mouselightdatabrowser/export-api:1.4
    hostname: export-api-1
    environment:
      NODE_ENV: production
    volumes:
       - /data/export:/opt/data/export
    networks:
      - back_tier
    links:
      - metrics-db

  export-api-2:
    image: mouselightdatabrowser/export-api:1.4
    hostname: export-api-2
    environment:
      NODE_ENV: production
    volumes:
       - /data/export:/opt/data/export
    networks:
      - back_tier
    links:
      - metrics-db

  proxy:
    image: mouselightdatabrowser/public-proxy:1.4
    ports:
      - 80:80
    networks:
      - back_tier
    environment:
      API_KEY: "${AMPLIFY_API_KEY}"
      AMPLIFY_IMAGENAME:
    links:
      - export-api-1
      - export-api-2
      - search-api-1
      - search-api-2
      - search-api-3
      - search-api-4
      - search-api-5
      - search-api-6
      - search-client-1
      - search-client-2

volumes:
  influx_data:
  influx_config:
  search_data:
  nginx_log:

networks:
  back_tier:
